default_platform(:android)

platform :android do
  desc "First lane for firebase distribution for MrDoctor app"
  lane :push_firebase_app_distribution do
    sh "flutter clean"
    sh "flutter build apk --release --flavor production --target lib/main_production.dart --no-tree-shake-icons"
    firebase_app_distribution(
    app: "1:700524598035:android:6c4b750f888f402271c0e6",
    testers: "yousseframadan573@gmail.com, yousseframadanelqursh@gmail.com",
    firebase_cli_token: "1//03fSMTiLSo8s8CgYIARAAGAMSNwF-L9IrYT5yrZBURV_O8cEq-goDUh2hYOXi_ghMlpyadumE5fUp2O0UVYGMMXtRmQZIe4hKjCA",
    android_artifact_type: "APK",
    android_artifact_path: "../build/app/outputs/flutter-apk/app-production-release.apk",
    upload_timeout: 1600,
    release_notes: "Link Github Actions with fastlane and distribute app on Firebase_App_Distribution"
  )
  end
end
